### ISSUE TITLE
Issue with the generated CWL when using multiple=True and required=False

### ISSUE THREAD

**Issue by fabricebrito** [Terradue/click2cwl#1]
The inputs binding is not done correctly when using multiple=True and required=False, i.e.:

```python
@click.option(
    "--s-expressions",
    "-s",
    "s_expressions",
    help="s expression defined as cbn:expression",
    required=False,
    multiple=True,
)
@click.pass_context
```

This shall generate the CWL:

```yaml
s_expressions:
      type:
      - 'null'
      - items: string
        type: array
        inputBinding:
          position: 4
          prefix: --s-expressions
```
